name: Release application
description:
  A GitHub Action to release build application to GitOps repository. Application
  uses direct push to branch or create pull request to release application. The
  action is designed to be used in CI/CD pipelines to automate the release
  process of applications to GitOps repositories.
author: Petr Hatoň

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  repository:
    description: The GitOps repository where the application will be released.
    required: true
  ref:
    description:
      The target branch in the GitOps repository where the application will be
      released.
    required: true
  path:
    description: The path for cloning the GitOps repository.
    required: false
    default: ''
  token:
    description:
      The GitHub token with permissions to push to the target branch in the
      GitOps repository.
    required: true
  github_enterprise_url:
    description:
      The URL of the GitHub Enterprise instance. This is required if you are
      using GitHub Enterprise.
    required: false
  deployment_file:
    description:
      The path to the deployment file that will be released to the GitOps
      repository.
    required: true
  jsonpath:
    description:
      The JSON path to extract the version from the deployment file. This is
      used to determine the version of the application being released.
    required: true
  value:
    description:
      The value to be extracted from the deployment file using the provided JSON
      path. This is used to determine the version of the application being
      released.
    required: true
  push:
    description:
      A boolean value indicating whether to push directly to the target branch
      (true) or create a pull request (false) for the release. Default is false.
    required: false
    default: 'false'
  pull_request:
    description:
      A boolean value indicating whether to create a pull request for the
      release. This is used when the push input is set to false. Default is
      true.
    required: false
    default: 'false'
  message:
    description:
      The commit message to use when pushing the release to the GitOps
      repository.
    required: false
    default: 'Release application'

# Define your outputs here.
outputs:
  time:
    description: The time when the action completed.

runs:
  using: node24
  main: dist/index.js
